export const SIGN_UP_CHANGE_EMAIL_TEXT = "SIGN_UP_CHANGE_EMAIL_TEXT"
export const SIGN_UP_CHANGE_PASSWORD_TEXT = "SIGN_UP_CHANGE_PASSWORD_TEXT"

export const LOG_IN_CHANGE_EMAIL_TEXT = "LOG_IN_CHANGE_EMAIL_TEXT"
export const LOG_IN_CHANGE_PASSWORD_TEXT = "LOG_IN_CHANGE_PASSWORD_TEXT"